### ISSUE TITLE
Logical CPU ID

### ISSUE THREAD

**Issue by AntoineD** [dogunter/omp_overhead#1]
Hello,

would it be possible to display the logical CPU ID (as shown by lstopo -l) instead of the physical one?

Cheers,
Antoine.

**Comment by AntoineD** [comment]
Hello,
is anybody looking here?
Cheers.

**Comment by AntoineD** [comment]
Hi David,

thanks a lot for your feedback, I really appreciate, your tool is the only one I know of that could provide this kind of informations.

I will test you corrections it after Xmas.

Happy holidays!

**Comment by dogunter** [comment]
Thanks again, Antoine. It was easier than I thought. The code will now accept the --logical flag for displaying logical PU and Core indices.

Cheers!

**Comment by dogunter** [comment]
--logical flag added.
